// The window's screens. The menu (NavRail) and the guide links share this list.
export type Screen =
  | 'home'
  | 'students'
  | 'import'
  | 'lockers'
  | 'allocate'
  | 'print'
  | 'letters'
  | 'reports'
  | 'history'
  | 'settings'
  | 'settings-labels'
  | 'settings-letters'
  | 'settings-codes'
  | 'settings-privacy'
  | 'settings-storage'
  | 'settings-computer'
  | 'setup'
  | 'rollover'
